#lang secd
(
 (INT_CONST 56)
 (FUN (IF0 ((FUN (INT_CONST 4) (ADD) (RETURN)) (INT_CONST 3) (APPLY))
           ((FUN (INT_CONST 8) (ADD) (RETURN)) (INT_CONST 6) (APPLY)))
      (RETURN))
 (INT_CONST 0)
 (APPLY)
 (ADD))